name: SysAdmincraft
description: Admin your server using Minecraft!
version: 0.1.0
main: pw.ian.sysadmincraft.SysAdmincraft
commands:
  top:
    description: Top
  pgrep:
    description: pgrep
  ps:
    description: ps
